name: lint

on:
  pull_request:

jobs:
  lint:
    environment:
      name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.3
        with:
          version: 10
      - name: pnpm install
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
